# Generated by Django 4.2.3 on 2023-07-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="姓名"),
                ),
                ("sex", models.SmallIntegerField(verbose_name="性别")),
                (
                    "phone",
                    models.CharField(max_length=11, null=True, verbose_name="电话"),
                ),
                (
                    "email",
                    models.CharField(max_length=60, null=True, verbose_name="邮箱"),
                ),
                (
                    "address",
                    models.CharField(max_length=60, null=True, verbose_name="地址"),
                ),
                (
                    "state",
                    models.CharField(max_length=60, null=True, verbose_name="状态"),
                ),
            ],
        ),
    ]
