# Generated by Django 4.2.3 on 2023-07-09 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 9, 10, 13, 53, 820868, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
